### ISSUE TITLE
Finding the volume/area in a enclosed contour

### ISSUE THREAD

**Issue by hisacro** [mauro3/WhereTheWaterFlows.jl#36]
Hello, I'm coming from [julia discourse](https://discourse.julialang.org/t/question-finding-number-of-closed-potential-contours-and-area-enclosed-by-them/124034). I tried your package but couldn't get `plt_catchments`  minding knowing where is it defined? `plt_func` seems to come from PyPlot but `plt_area` too.

Any pointers will be helpful regarding above as well as the original question.

In the [example.jl](https://github.com/mauro3/WhereTheWaterFlows.jl/blob/master/examples/example.jl) too,
`plt_catchments`, `plt_area`, `plt_it` are not defined. I suppose it comes with PyPlot. Current version,

```
julia> Pkg.status("PyPlot")
Status `~/.julia/environments/v1.9/Project.toml`
⌃ [d330b81b] PyPlot v2.11.2
```

**Comment by mauro3** [comment]
The plotting now happens with Makie.  If you "using" GLMakie or CairoMakie the plotting should work. (If you want PyPlot, you need to go back to version 0.10).
